### ISSUE TITLE
[Feature] ci/cd

### ISSUE THREAD

**Issue by julia-heo** [EWHA-LUX/ONCE-BE#1]
### 🚀 Feature
> ci cd 코드 추가

### ✅ Tasks
- [x] .github/workflows/gradle.yml
- [x] Dockerfile
- [x] docker-compose.yml
- [x] Repository secrets 추가
- [x] deploy 브랜치 추가
