### ISSUE TITLE
[Feature] 프로필 이미지 수정, 회원 탈퇴

### ISSUE THREAD

**Issue by julia-heo** [EWHA-LUX/ONCE-BE#10]
### 🚀 Feature
> 유저 관련 api 구현

### ✅ Tasks
- [x] S3 연결
- [x] 회원가입 시 기본 이미지 등록
- [x] 프로필 이미지 수정 api
- [x] 회원 탈퇴 api
