### ISSUE TITLE
[Fix] 챗봇 예외 처리

### ISSUE THREAD

**Issue by julia-heo** [EWHA-LUX/ONCE-BE#100]
### 🚀 Fix
> 1. 카드 추천 결과 할인금액이 0인 경우의 챗봇 추천
> 2. 실적을 모두 채운 경우의 알림

### ✅ Tasks
- [x] 1-1 주카드가 한장이라면 그 카드 반환
- [x] 1-2 주카드가 여러장이라면 그 중 실적 가장 많이남은거
- [x] 1-3 주카드가 없다면 나머지 카드 중 실적 가장 많이 남은거
- [x] 2 실적을 모두 채운 경우 알림 생성x
- [ ] 알림/챗봇 멘트 수정
