### ISSUE TITLE
[Feature] 알림 조회, 알림 상세 조회 api 구현

### ISSUE THREAD

**Issue by julia-heo** [EWHA-LUX/ONCE-BE#12]
### 🚀 Feature
> 알림 관련 api 구현

### ✅ Tasks
1차
- [x] 알림, 단골가게, 가게 엔티티
- [x] 카드 엔티티 위치 변경
- [x] 알림 조회 api (list)
- [x] 알림 상세 조회 api

2차
- [x] 알림 리스트 조회 닉네임 추가
- [x] 알림 응답 시간 수정
