### ISSUE TITLE
[Feature] 챗봇 카드 추천 API 구현

### ISSUE THREAD

**Issue by Haewonny** [EWHA-LUX/ONCE-BE#41]
### 🚀 Feature
> 챗봇 카드 추천 API

### ✅ Tasks
1차
- [x] Gemini RestTemplate 생성
- [x] Openai RestTemplate 생성
- [x] Gemini API Key 등록
- [x] Openai API Key 등록
- [x] 비즈니스 로직 구현

2차
- [x] 보유 카드의 benefit_summary 조회
- [x] 프롬프트 작성

3차
- [x] 응답에 `cardCompany` 추가
