### ISSUE TITLE
[Feature] 알림 생성

### ISSUE THREAD

**Issue by julia-heo** [EWHA-LUX/ONCE-BE#43]
### 🚀 Feature
> 알림생성 구현

### ✅ Tasks
- [x] 주카드 등록
- [x] 주카드 실적 알림
- [x] 목표 응원 알림
- [ ] 단골 가게 알림
- [x] CODEF연결
- [x] FCM설정
