### ISSUE TITLE
[Feature] ERD 수정 반영

### ISSUE THREAD

**Issue by Haewonny** [EWHA-LUX/ONCE-BE#52]
### 🚀 Feature
> ERD 수정 반영

### ✅ Tasks
- [x] `card` 엔티티 수정
- [x] `event_summary` 엔티티 추가
- [x] `benefit_summary` 엔티티 추가
- [x] 연관관계 설정
