### ISSUE TITLE
[Fix] 크롤링 자동화 오류 해결

### ISSUE THREAD

**Issue by Haewonny** [EWHA-LUX/ONCE-BE#66]
### 🔧 Fix
> 자동화를 위한 파이썬 파일의 실행 오류 해결

### ✅ Tasks
1차
- [x] python, pip 설치, requirements.txt 
- [x] "python" → "python3" 변경
- [x] 전체 경로 확인
- [x] 크롬 실행 경로 변경
- [x] chrome_options 변경 

2차
- [x] 크롤링 코드 `flush=True` 추가하기
- [x] docker-compose 업데이트
- [x] ProcessBuilder `-u` 옵션 추가

3차
- [x] 롯데 크롤링 S3

4차
- [x] 도커 컨테이너 시간 KST로 변경
- [x] 롯데 config.ini 환경변수 설정
- [x] 크롤링 코드 경로 수정
