### ISSUE TITLE
[Feature] 홈화면 api 구현

### ISSUE THREAD

**Issue by julia-heo** [EWHA-LUX/ONCE-BE#8]
### 🚀 Feature
> 홈화면 관련 api 구현

### ✅ Tasks
- [x] 챗봇 카드 추천
- [x] 홈화면 기본 정보
- [x] 결제 여부 변경

### 💬 ETC
알림 관련 api 제외
